server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.103:3306/hmdp?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Qaq123456-
  redis:
    host: 192.168.0.103
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
#    sentinel:
#      master: mymaster #指定master名称
#      nodes: # 指定redis-sentinel的集群信息
#        - 192.168.0.103:27001
#        - 192.168.0.103:27002
#        - 192.168.0.103:27003
  jackson:
    default-property-inclusion: NON_NULL # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug